=== JKomskis/Resume/schemas/resume.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://github.com/JKomskis/Resume/blob/main/schemas/resume.schema.json",
    "title": "Resume",
    "description": "A resume describing one's education, skills, employment, projects, etc.",
    "type": "object",
    "properties": {
        "$schema": {
            "description": "The JSON schema for this resume",
            "type": "string"
        },
        "meta": {
            "description": "Metadata about the resume",
            "type": "object",
            "properties": {
                "version": {
                    "description": "The semantic version of this resume.",
                    "type": "string",
                    "pattern": "^[0-9]+\\.[0-9]+\\.[0-9]+$"
                },
                "date": {
                    "description": "The date on which this file was authored or last revised.",
                    "type": "string",
                    "format": "date"
                }
            },
            "additionalProperties": false,
            "required": [
                "version",
                "date"
            ]
        },
        "info": {
            "description": "Basic resume information",
            "type": "object",
            "properties": {
                "firstname": {
                    "description": "First name",
                    "type": "string"
                },
                "lastname": {
                    "description": "Last name",
                    "type": "string"
                },
                "github": {
                    "description": "Github profile link",
                    "type": "string",
                    "format": "uri"
                },
                "website": {
                    "description": "Personal website link",
                    "type": "string",
                    "format": "uri"
                }
            },
            "additionalProperties": false,
            "required": [
                "firstname",
                "lastname"
            ]
        },
        "contact": {
            "description": "Contact information",
            "type": "object",
            "properties": {
                "email": {
                    "description": "Email address",
                    "type": "string",
                    "format": "email"
                },
                "phone": {
                    "description": "Phone number",
                    "type": "string",
                    "pattern": "^[0-9]{3}-[0-9]{3}-[0-9]{4}$"
                },
                "linkedin": {
                    "description": "LinkedIn profile link",
                    "type": "string",
                    "format": "uri"
                }
            },
            "additionalProperties": false
        },
        "education": {
            "description": "Education history",
            "type": "array",
            "items": {
                "$ref": "#/$defs/education"
            },
            "uniqueItems": true
        },
        "skills": {
            "description": "Skills",
            "type": "array",
            "items": {
                "$ref": "#/$defs/skill"
            },
            "uniqueItems": true
        },
        "experience": {
            "description": "Employment history",
            "type": "array",
            "items": {
                "$ref": "#/$defs/experience"
            },
            "uniqueItems": true
        },
        "projects": {
            "description": "Projects",
            "type": "array",
            "items": {
                "$ref": "#/$defs/project"
            },
            "uniqueItems": true
        },
        "leadership": {
            "description": "Leadership experience",
            "type": "array",
            "items": {
                "$ref": "#/$defs/leadership"
            },
            "uniqueItems": true
        }
    },
    "required": [
        "meta",
        "info",
        "contact"
    ],
    "additionalProperties": false,
    "$defs": {
        "date": {
            "description": "A date formatted as YYYY-MM",
            "type": "string",
            "pattern": "^[0-9]{4}-(0[0-9]|1[0-2])$"
        },
        "location": {
            "description": "A geographical location made up of city, state, and country (optional).",
            "type": "object",
            "properties": {
                "city": {
                    "description": "City",
                    "type": "string"
                },
                "state": {
                    "description": "State",
                    "type": "string"
                },
                "country": {
                    "description": "Country",
                    "type": "string"
                }
            },
            "additionalProperties": false,
            "required": [
                "city",
                "state"
            ]
        },
        "position": {
            "description": "A position held at a company/organization",
            "type": "object",
            "properties": {
                "title": {
                    "description": "Title of the position",
                    "type": "string"
                },
                "start": {
                    "description": "Date started working in the position",
                    "$ref": "#/$defs/date"
                },
                "end": {
                    "description": "Date stopped working in the position",
                    "$ref": "#/$defs/date"
                }
            },
            "additionalProperties": false,
            "required": [
                "title",
                "start"
            ]
        },
        "education": {
            "description": "Education entry",
            "type": "object",
            "properties": {
                "name": {
                    "description": "Name of Institution",
                    "type": "string"
                },
                "degree": {
                    "description": "Degree earned / to be earned",
                    "type": "string"
                },
                "location": {
                    "description": "Location while attending the institution",
                    "$ref": "#/$defs/location"
                },
                "graduated": {
                    "description": "Date graduated / expected to graduate",
                    "$ref": "#/$defs/date"
                },
                "highlights": {
                    "description": "Key points about the author's achievements while attending this institution",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            },
            "additionalProperties": false,
            "required": [
                "name",
                "degree",
                "location",
                "graduated",
                "highlights"
            ]
        },
        "skill": {
            "description": "A skill category of the author, along with example of it",
            "type": "object",
            "properties": {
                "category": {
                    "description": "Name of the skill",
                    "type": "string"
                },
                "examples": {
                    "description": "Examples of the skill in use",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "uniqueItems": true,
                    "minItems": 1
                }
            },
            "additionalProperties": false,
            "required": [
                "category",
                "examples"
            ]
        },
        "experience": {
            "description": "Employment entry",
            "type": "object",
            "properties": {
                "company": {
                    "description": "Name of the company",
                    "type": "string"
                },
                "location": {
                    "description": "Location during the employment",
                    "$ref": "#/$defs/location"
                },
                "positions": {
                    "description": "Position held at the company",
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/position"
                    },
                    "uniqueItems": true,
                    "minItems": 1
                },
                "highlights": {
                    "description": "Key points about the author's achievements while working in this role",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            },
            "additionalProperties": false,
            "required": [
                "company",
                "location",
                "positions",
                "highlights"
            ]
        },
        "project": {
            "description": "A project the author has worked on",
            "type": "object",
            "properties": {
                "name": {
                    "description": "Name of the project",
                    "type": "string"
                },
                "context": {
                    "description": "Context in which the project was done, e.g. class project or personal project",
                    "type": "string"
                },
                "start": {
                    "description": "Date started working on the project",
                    "$ref": "#/$defs/date"
                },
                "end": {
                    "description": "Date stopped working on the project",
                    "$ref": "#/$defs/date"
                },
                "highlights": {
                    "description": "Key points about the project",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            },
            "additionalProperties": false,
            "required": [
                "name",
                "context",
                "start",
                "highlights"
            ]
        },
        "leadership": {
            "description": "Leadership history entry",
            "type": "object",
            "properties": {
                "organization": {
                    "description": "Name of the organization",
                    "type": "string"
                },
                "location": {
                    "description": "Location while the position was held",
                    "$ref": "#/$defs/location"
                },
                "positions": {
                    "description": "Position held at the organization",
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/position"
                    },
                    "uniqueItems": true,
                    "minItems": 1
                },
                "highlights": {
                    "description": "Key points about the author's achievements while working in this role",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            },
            "additionalProperties": false,
            "required": [
                "organization",
                "location",
                "positions",
                "highlights"
            ]
        }
    }
}

=== JKomskis/Resume/resume_one_pager.json
{
    "$schema": "schemas/resume.schema.json",
    "meta": {
        "version": "1.0.0",
        "date": "2024-11-09"
    },
    "info": {
        "firstname": "Joseph",
        "lastname": "Komskis",
        "github": "https://github.com/JKomskis",
        "website": "https://komsk.is"
    },
    "contact": {
        "linkedin": "https://linkedin.com/in/joseph-komskis"
    },
    "education": [
        {
            "name": "Georgia Institute of Technology",
            "degree": "Master of Science in Computer Science",
            "location": {
                "city": "Atlanta",
                "state": "GA"
            },
            "graduated": "2022-05",
            "highlights": [
                "GPA: 4.0",
                "Specialization: Computing Systems",
                "Relevant Coursework: Advanced Operating Systems, System Design in Cloud Computing, Database System Implementation, High Performance Computer Architecture, Computer Networks, Graduate Algorithms, Programming Languages"
            ]
        },
        {
            "name": "University of Florida",
            "degree": "Bachelor of Science in Computer Science",
            "location": {
                "city": "Gainesville",
                "state": "FL"
            },
            "graduated": "2020-05",
            "highlights": [
                "GPA: 3.98; Cum Laude; Honors Program",
                "Minor: Business Administration"
            ]
        }
    ],
    "skills": [
        {
            "category": "Languages",
            "examples": [
                "C++",
                "Python",
                "Java",
                "PowerShell",
                "SQL",
                "Rust",
                "Go",
                "HTML",
                "CSS",
                "JavaScript",
                "React",
                "Kotlin",
                "Haskell"
            ]
        },
        {
            "category": "Tools/Technologies",
            "examples": [
                "Git",
                "GitHub",
                "Spark",
                "Hadoop",
                "Docker",
                "Etcd",
                "MongoDB",
                "NodeJS",
                "Azure",
                "LaTeX",
                "K8s",
                "ANTLR"
            ]
        },
        {
            "category": "Processes",
            "examples": [
                "Agile Development",
                "Scrum",
                "Kanban",
                "Code Review",
                "CI/CD",
                "TDD",
                "ER Modeling",
                "UML Modeling"
            ]
        }
    ],
    "experience": [
        {
            "company": "Microsoft",
            "location": {
                "city": "Redmond",
                "state": "WA"
            },
            "positions": [
                {
                    "title": "Software Engineer II",
                    "start": "2024-09"
                },
                {
                    "title": "Software Engineer",
                    "start": "2022-08",
                    "end": "2024-09"
                }
            ],
            "highlights": [
                "Worked on the ADLS Gen2 team",
                "Reduced recursive listing latency by 6x-12x by optimizing namespace calls and reducing name resolution calls",
                "Improved system performance by implementing a 0-copy interface for entities"
            ]
        },
        {
            "company": "Georgia Institute of Technology",
            "location": {
                "city": "Atlanta",
                "state": "GA"
            },
            "positions": [
                {
                    "title": "Graduate Teaching Assistant - Advanced Operating Systems",
                    "start": "2022-01",
                    "end": "2022-05"
                },
                {
                    "title": "Graduate Teaching Assistant - Introduction to Database Systems",
                    "start": "2021-01",
                    "end": "2021-12"
                }
            ],
            "highlights": [
                "Built an autograding pipeline for student projects using Azure Batch to provide students with immediate grading feedback",
                "Created and graded phases of a semester group project focused on designing and implementing a database application",
                "Drafted exam questions and grading rubrics; graded exams"
            ]
        },
        {
            "company": "Microsoft",
            "location": {
                "city": "Ft Lauderdale",
                "state": "FL"
            },
            "positions": [
                {
                    "title": "Software Engineering Intern (Virtual Internship)",
                    "start": "2021-05",
                    "end": "2021-08"
                }
            ],
            "highlights": [
                "Designed and implemented a proof-of-concept platform for moving compute heavy tasks from Azure Storage using Spark",
                "Analyzed several deployment options and weighed their tradeoffs in several aspects, such as control, scalability, and security",
                "Tested the performance of the existing query acceleration feature and proposed a new hybrid query processing approach"
            ]
        }
    ],
    "projects": [
        {
            "name": "MapReduce in Go",
            "context": "System Design in Cloud Computing Pair Project (Go)",
            "start": "2022-01",
            "end": "2022-05",
            "highlights": [
                "Recreated MapReduce in Go, with master failover capabilities, and deployed on Azure Kubernetes Service",
                "Implemented the logic for master failover and communication of tasks from leader node to worker nodes"
            ]
        },
        {
            "name": "SQL Typecheck",
            "context": "Programming Languages Term Project (Python)",
            "start": "2022-01",
            "end": "2022-05",
            "highlights": [
                "Defined an abstract syntax and typing rules for a subset of SQL",
                "Implemented and unit tested a parser and type checker for queries"
            ]
        }
    ],
    "leadership": [
        {
            "organization": "University of Florida Programming Team",
            "location": {
                "city": "Gainesville",
                "state": "FL"
            },
            "positions": [
                {
                    "title": "Captain",
                    "start": "2019-01",
                    "end": "2020-05"
                },
                {
                    "title": "Lead",
                    "start": "2018-09",
                    "end": "2019-01"
                }
            ],
            "highlights": [
                "Competed in ACM Programming Competitions focusing on data structures and algorithms",
                "Led meetings and taught competitive programming topics such as algorithm complexity",
                "Organized an interview workshop to teach tips and techniques for behavioral and technical questions",
                "SER 2017: 20/47    SER 2018: 10/36    SER 2019: 11/36"
            ]
        }
    ]
}
